# Generated by Django 4.1 on 2022-08-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictususer', '0002_profile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictususer.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='camera',
            field=models.CharField(choices=[('1', 'Nikon FM2'), ('2', 'Canon AE-1'), ('3', 'Leica M3'), ('4', 'Pentax Me Super'), ('5', 'Minolta X-300'), ('6', 'Minolta X-700'), ('7', 'Ricoh ff-9d'), ('8', 'Contax T3'), ('9', 'Samsung Kenox M70 super '), ('10', 'olympus mju 2'), ('11', 'Canon autoboy tele'), ('12', 'Canon autoboy luna 35'), ('13', 'Canon autoboy 3'), ('14', 'Canon autoboy 2'), ('15', 'Fuji Klasse W'), ('16', 'Lomo LC-A'), ('17', 'Olympus Pen EE-2'), ('18', 'Yashica Electro 35'), ('19', 'Contax G1'), ('20', 'Konica C35'), ('21', 'Toma m 616')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='film',
            field=models.CharField(choices=[('1', 'Kodak colorplus 200'), ('2', 'Kodak gold 200'), ('3', 'Kodak proimage 100'), ('4', 'Kodak ultramax 400'), ('5', 'Kodak ektar 100'), ('6', 'Kodak portra 160'), ('7', 'Fujicolor 100'), ('8', 'Fuji Superia X-TRA 400'), ('9', 'Fujifilm Superia Premium 400'), ('10', 'Fujifilm C200'), ('11', 'Lomography color negative 100'), ('12', 'Lomography color negative 400'), ('13', 'Lomography color negative 800'), ('14', 'Kodak Portra 800'), ('15', 'Kodak Portra 400'), ('16', 'Lomography lomochrome purple xr100_400*'), ('17', 'Kodak Ektachrome E100 '), ('18', 'Fujifilm Velvia 100'), ('19', 'Fujifilm Provia 100F'), ('20', 'Kentmere Pan 400'), ('21', 'Fomapan R100')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_phosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
