# Generated by Django 4.1 on 2022-08-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictususer', '0002_profile_email'),
        ('pictusapp', '0005_remove_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_nickname', to='pictususer.profile'),
        ),
    ]
